# ToxTunnel Client Configuration
# Generated by tox-tunnel-ops skill
#
# Usage: toxtunnel -m client -c client.yaml

mode: client

# Directory for Tox identity (tox_save.dat) and bootstrap cache
# macOS:  ~/Library/Application Support/toxtunnel/client
# Linux:  ~/.config/toxtunnel/client
# Windows: %APPDATA%\toxtunnel\client
data_dir: {{DATA_DIR}}

logging:
  level: {{LOG_LEVEL|info}}
  # file: /var/log/toxtunnel/client.log   # uncomment for file logging

tox:
  udp_enabled: true
  bootstrap_mode: {{BOOTSTRAP_MODE|auto}}

client:
  # Paste the server's 76-character Tox ID here.
  # You can find it in the server's startup log output.
  server_id: {{SERVER_ID|<PASTE_SERVER_TOX_ID_HERE>}}

  # Port forwarding rules: local_port on this machine → remote_host:remote_port on server side
  forwards:
{{#FORWARDS}}
    - local_port: {{LOCAL_PORT}}
      remote_host: {{REMOTE_HOST}}
      remote_port: {{REMOTE_PORT}}
{{/FORWARDS}}

{{#PIPE_TARGET}}
  # Pipe mode (alternative to forwards, used with SSH ProxyCommand)
  pipe:
    remote_host: {{PIPE_REMOTE_HOST}}
    remote_port: {{PIPE_REMOTE_PORT}}
{{/PIPE_TARGET}}
{{^PIPE_TARGET}}
  # Pipe mode (uncomment for SSH ProxyCommand usage):
  # pipe:
  #   remote_host: 127.0.0.1
  #   remote_port: 22
{{/PIPE_TARGET}}
