# ToxTunnel Access Control Rules
# Generated by tox-tunnel-ops skill
#
# Each rule binds to a specific friend's 64-character hex public key.
# Wildcards are NOT supported for friend identity.
#
# Evaluation order:
#   1. Find the rule matching the friend's public key (exact match)
#   2. Check deny rules first (deny takes precedence)
#   3. Check allow rules
#   4. No match → default deny
#
# Host patterns: "*" wildcard supported (e.g., "*.example.com", "192.168.*.*")
# Ports: list specific ports, or use empty list [] to mean "all ports"
#
# Template variables:
#   {{FRIEND_PK}}    — 64-char hex public key (required)
#   {{FRIEND_LABEL}} — comment label for the friend (optional, human-readable)
#   {{HOST}}         — target hostname or IP pattern
#   {{PORTS}}        — YAML list: [22, 80, 443] for specific ports, or [] for all ports
#
# Place this file alongside server.yaml and reference it with:
#   server:
#     rules_file: rules.yaml
#
# v0.4: anti-DoS rate-limit defaults (apply to every friend without a
# per-friend `rate_limit:` block). Uncomment to enable. Start with
# `mode: report` to size the limits against real traffic, then flip to
# `mode: enforce`.
#
# rate_limit_defaults:
#   mode: enforce
#   open_per_sec: 10
#   open_burst: 50
#   bytes_per_sec: 10485760     # 10 MiB/s steady-state
#   bytes_burst: 33554432       # 32 MiB allowed burst
#   max_concurrent_tunnels: 100

rules:
{{#RULES}}
  - friend: "{{FRIEND_PK}}"    # {{FRIEND_LABEL}}
    # v0.4: optional per-friend rate-limit override (additive over defaults).
    # rate_limit:
    #   mode: enforce
    #   bytes_per_sec: 104857600
    #   max_concurrent_tunnels: 200
    allow:
{{#ALLOW}}
      - host: "{{HOST}}"
        ports: {{PORTS}}
{{/ALLOW}}
{{#DENY}}
    deny:
      - host: "{{HOST}}"
        ports: {{PORTS}}
{{/DENY}}
{{/RULES}}
