# ToxTunnel Access Control Rules
# Generated by tox-tunnel-ops skill
#
# Each rule binds to a specific friend's 64-character hex public key.
# Wildcards are NOT supported for friend identity.
#
# Evaluation order:
#   1. Find the rule matching the friend's public key (exact match)
#   2. Check deny rules first (deny takes precedence)
#   3. Check allow rules
#   4. No match → default deny
#
# Host patterns: "*" wildcard supported (e.g., "*.example.com", "192.168.*.*")
# Ports: list specific ports, or use empty list [] to mean "all ports"
#
# Template variables:
#   {{FRIEND_PK}}    — 64-char hex public key (required)
#   {{FRIEND_LABEL}} — comment label for the friend (optional, human-readable)
#   {{HOST}}         — target hostname or IP pattern
#   {{PORTS}}        — YAML list: [22, 80, 443] for specific ports, or [] for all ports
#
# Place this file alongside server.yaml and reference it with:
#   server:
#     rules_file: rules.yaml

rules:
{{#RULES}}
  - friend: "{{FRIEND_PK}}"    # {{FRIEND_LABEL}}
    allow:
{{#ALLOW}}
      - host: "{{HOST}}"
        ports: {{PORTS}}
{{/ALLOW}}
{{#DENY}}
    deny:
      - host: "{{HOST}}"
        ports: {{PORTS}}
{{/DENY}}
{{/RULES}}
