# ToxTunnel Server Configuration
# Generated by tox-tunnel-ops skill
#
# Usage: toxtunnel -m server -c server.yaml
# After starting, note the Tox ID printed in the log — the client needs it.

mode: server

# Directory for Tox identity (tox_save.dat) and bootstrap cache
# macOS:  ~/Library/Application Support/toxtunnel/server
# Linux:  ~/.config/toxtunnel/server
# Windows: %APPDATA%\toxtunnel\server
data_dir: {{DATA_DIR}}

logging:
  level: {{LOG_LEVEL|info}}
  # file: /var/log/toxtunnel/server.log   # uncomment for file logging

tox:
  udp_enabled: true
  tcp_port: {{TCP_PORT|33445}}
  # auto: connect via public DHT nodes (requires internet)
  # lan:  LAN-only discovery (no internet needed, both machines must be on same subnet)
  bootstrap_mode: {{BOOTSTRAP_MODE|auto}}
  # Manual bootstrap nodes (only needed for air-gapped or custom setups):
  # bootstrap_nodes:
  #   - address: 198.199.98.108
  #     port: 33445
  #     public_key: <64-hex-chars>

{{#RULES_FILE}}
server:
  rules_file: {{RULES_FILE}}
{{/RULES_FILE}}
{{^RULES_FILE}}
# Access control rules (recommended for production use)
# server:
#   rules_file: rules.yaml
{{/RULES_FILE}}
