# ToxTunnel Server Configuration
# Generated by tox-tunnel-ops skill
#
# Usage: toxtunnel -m server -c server.yaml
# After starting, note the Tox ID printed in the log — the client needs it.

mode: server

# Directory for Tox identity (tox_save.dat) and bootstrap cache
# macOS:  ~/Library/Application Support/toxtunnel/server
# Linux:  ~/.config/toxtunnel/server
# Windows: %APPDATA%\toxtunnel\server
data_dir: {{DATA_DIR}}

# Service / daemon policy when run under `--service` (systemd, launchd, SCM).
# Server defaults to "online" — packaged installs come up reachable. Flip
# auto_start: false to ship a server install that idles until manually enabled.
# service:
#   auto_start: true            # server installs default to online
#   allow_client_daemon: false  # ignored in server mode

logging:
  level: {{LOG_LEVEL|info}}
  # file: /var/log/toxtunnel/server.log   # uncomment for file logging

# Prometheus /metrics endpoint (opt-in). Off by default.
# KEEP the listen address on loopback unless the scraper is on a trusted
# network — Prometheus exposition has no built-in auth.
# metrics:
#   enabled: false
#   listen: 127.0.0.1:9100
#   path: /metrics

# Local IPC for `toxtunnel inspect` (read-only, never network-exposed).
# Default-on; set enabled: false to disable.
# inspect:
#   enabled: true

# Tunnel data-path tunables. Defaults are sane for most users.
# tunnel:
#   coalesce_max_delay_us: 200    # default-on small-write coalescing
#   coalesce_max_bytes: 1362      # ≤ Tox 1367-byte frame limit
#   coalesce_mode: fixed          # v0.4: fixed (default) | adaptive | bypass | drain
#   keepalive_interval_seconds: 0 # v0.4: 0=off; >0 sends PING/PONG every Ns,
#                                 # declares peer dead after 3× of no PONG.
#   idle_timeout_seconds: 0       # 0 = disabled; SERVER deployments are
#                                 # encouraged to set this (e.g. 600–1800) to
#                                 # reap tunnels whose peer abandoned the TCP
#                                 # connection without a clean close.
#   reaper_tick_seconds: 10       # reaper wake-up interval
#   resume:                       # v0.4: tunnel fast-reattach (opt-in)
#     enabled: false              # opcodes wire-inactive when false
#     max_age_seconds: 300        # drop saved entries older than this
#     on_gap: passthrough         # passthrough | close

# v0.4 stability + performance blocks (all opt-in; defaults preserve v0.3.0).
# watchdog:
#   enabled: true                 # in-process tox-thread wedge detector
#   deadline_seconds: 30          # std::abort() if heartbeat stalls past this
#   systemd_notify: true          # sd_notify(WATCHDOG=1) on Linux only
# flow_control:
#   mode: bdp                     # bdp (default since v0.4.1) | fixed (v0.3.0 cadence)
#   send_window_min_bytes: 65536  # 64 KiB clamp floor (bdp mode)
#   send_window_max_bytes: 4194304   # 4 MiB clamp ceiling (bdp mode)
#   safety_factor_x100: 150       # 1.5× BDP headroom
#   fixed_window_bytes: 262144    # 256 KiB — used in fixed mode

tox:
  udp_enabled: true
  tcp_port: {{TCP_PORT|33445}}
  # auto: connect via public DHT nodes (requires internet)
  # lan:  LAN-only discovery (no internet needed, both machines must be on same subnet)
  bootstrap_mode: {{BOOTSTRAP_MODE|auto}}
  # Manual bootstrap nodes (only needed for air-gapped or custom setups):
  # bootstrap_nodes:
  #   - address: 198.199.98.108
  #     port: 33445
  #     public_key: <64-hex-chars>

{{#RULES_FILE}}
server:
  rules_file: {{RULES_FILE}}
  # System-info disclosure to clients via INFO_REQUEST/INFO_REPLY.
  # Defaults are all false (server discloses nothing). Opt in per field if
  # operators of connecting clients should be able to see this metadata.
  # disclose:
  #   hostname: false
  #   os: false
  #   os_version: false
  #   arch: false
  #   uptime: false
  #   toxtunnel_version: false
{{/RULES_FILE}}
{{^RULES_FILE}}
# Access control rules (recommended for production use)
# server:
#   rules_file: rules.yaml
#   disclose:
#     hostname: false
#     os: false
#     os_version: false
#     arch: false
#     uptime: false
#     toxtunnel_version: false
{{/RULES_FILE}}
