set(CPACK_PACKAGE_NAME "ToxTunnel")
set(CPACK_PACKAGE_VENDOR "ToxTunnel")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_CONTACT "maintainers@toxtunnel.local")
set(CPACK_COMPONENTS_ALL toxtunnel-runtime)

set(CPACK_PACKAGE_FILE_NAME
    "toxtunnel-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(CPACK_GENERATOR "DEB;RPM;TGZ")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libsodium23")
    set(CPACK_RPM_PACKAGE_REQUIRES "libsodium")
endif()

if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(CPACK_GENERATOR "productbuild;TGZ")
endif()

if(WIN32)
    set(CPACK_GENERATOR "NSIS;ZIP")
    set(CPACK_NSIS_DISPLAY_NAME "ToxTunnel")
    set(CPACK_NSIS_PACKAGE_NAME "ToxTunnel")
endif()

include(CPack)
